### ISSUE TITLE
Overlooked issue.

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [Bennyboy1695/AutoJumpAutoOff#1]
The Auto Jump Auto Off toast is stuck in the top right. The only way for it to change is to restart your game. This kind of messes with my OCD. Try to make it stay there but then slide away, similar to an advancement

**Comment by Bennyboy1695** [comment]
Uploading a new version to curseforge now with toasts removed, wasn't aware they were broken as when i added them it worked fine 😛

**Comment by CrankySupertoonArchive** [comment]
Thank you
